###
#   Database Settings
###
spring:
  datasource:
    url: jdbc:p6spy:h2:mem:persistence;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  jpa:
    database: h2
    hibernate:
      ddl-auto: update

  ###
  #   H2 Settings
  ###
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false